name: Newman Run

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      newman:
        description: 'Run'
        required: false
        default: 'Run action'

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        env:
          POSTMAN_API_KEY: ${{ secrets.INSURANCE_API_KEY }}
        with:
          collection: https://api.getpostman.com/collections/16873021-1d4bf222-4a7e-4c67-9098-519bd03dde67?apikey=$POSTMAN_API_KEY
          environment: https://api.getpostman.com/environments/16871434-02d5b697-755d-4540-b002-5f1896aa7804?apikey=$POSTMAN_API_KEY
